<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.materin.tech</groupId>
        <artifactId>dfx-component</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    <artifactId>dfx-access-mqtt</artifactId>
    <name>Materin DFX Access MQTT</name>
    <description>DFX MQTT 接入实现（独立共享订阅消费 dfx 主题）</description>
    <dependencies>
        <dependency>
            <groupId>com.materin.tech</groupId>
            <artifactId>dfx-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.hivemq</groupId>
            <artifactId>hivemq-mqtt-client</artifactId>
            <version>1.3.5</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
