<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.materin.tech</groupId>
        <artifactId>materin-backend</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>system</artifactId>
    <packaging>pom</packaging>
    <name>Materin System</name>
    <description>系统板块：RBAC、认证、组织等平台自身管理能力</description>

    <modules>
        <module>system-rbac</module>
        <module>system-openapi</module>
    </modules>
</project>
